
# SEO settings
title: "major13ua"
title2: "space" # default: ""
description: "Just another minimalist Jekyll theme that focuses on technical writing."
keywords: "java, js, camel, angular, git"
url: https://major13ua.github.io # site url
baseurl: null # apply repo name if use it under gh-pages branch "/thinkspace"
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: https://github.com/major13ua/
disqus_shortname: ""
twitter_username: ""
comments: false

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Chupryna Ievgen"
  job      : "R&D Software Engineer and Delivery Manager"
  bio      : "bio TODO"
  thumb    : /images/author.jpg
  email    : ichupryna@gmail.com
  url      : https://major13ua.github.io
  github   : https://major13ua.github.io
  twitter  :
  facebook :
  linkedin :

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@HeiswayiNrird"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
